---
configure_fonts: true
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/armarquez/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/dotfiles"
dotfiles_repo_version: master
dotfiles_home: "~" 

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bazelisk
  # - bash-completion
  # - doxygen
  - fzf
  # - gettext
  # - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - ical-buddy
  - iperf
  - libevent
  - sqlite
  - nmap
  # - node
  - nvm
  # - php
  # - pngpaste
  - podman
  - ssh-copy-id
  - readline
  - ripgrep
  - rsync
  - openssl
  - pv
  - stow
  - tldr
  - wget
  # - wrk
  - zsh
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - bettertouchtool
  # - chromedriver
  # - docker
  - dropbox
  - firefox
  - google-chrome
  - google-drive
  # - handbrake
  - helpwire-operator
  - iterm2
  # - licecap
  # - sequel-ace
  - slack
  # - sublime-text
  - tailscale-app
  - transmit
  - visual-studio-code

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# iTerm2 configuration
iterm2_profiles_source_dir: "{{ playbook_dir }}/files/iterm2"
iterm2_dynamic_profiles_dest_dir: "~/Library/Application Support/iTerm2/DynamicProfiles"

# OSX configuration
osx_script_source: "{{ playbook_dir }}/files/scripts/.osx"
osx_script_dest: "~/.osx"
