---
- name: Copy OSX configuration script files to the appropriate directory.
  ansible.builtin.copy:
    src: "{{ osx_script_source }}"
    dest: "{{ osx_script_dest }}"
    mode: '0644'
  become: false

# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
